AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patient-checkout

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    

Resources:

  PatientCheckoutTopic:
    Type: AWS::SNS::Topic

  PatientCheckoutBucket:
    Type: AWS::S3::Bucket 
    Properties: 
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
    
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patient-checkout/
      Handler: patient_checkout.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PatientCheckoutTopic.TopicName
      Environment:
        Variables:
          PATIENT_CHECKOUT_TOPIC: !Ref PatientCheckoutTopic
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*


  BillManagementFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: patient-checkout/
      Handler: bill_management.lambda_handler   
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref PatientCheckoutTopic
