AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  patient-checkout

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    

Resources:

  PatientCheckoutBucket:
    Type: AWS::S3::Bucket 
    Properties: 
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
    
  PatientCheckoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: patient-checkout/
      Handler: patient_checkout.lambda_handler
      Runtime: python3.8
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PatientCheckoutBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PatientCheckoutBucket
