version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "first-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vczkj3abfc5w"
s3_prefix = "first-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
